plugins:
  - jekyll-remote-theme
  - jekyll-include-cache

remote_theme: ucsb-cs-course-repos/course-repo-jekyll-theme

url: https://ucsb-cs9.github.io
baseurl: "/w25"

course: "CS 9"
qtr: "W25"
instructor: "Richert Wang" 
quarter: "Winter 2025"
piazza_url: 
gauchospace_course_page:
gradescope_class_url:

github_url: https://github.com/ucsb-cs9/w25

start_week: 0
start_date: 2025-01-05 00:00:00.00-7:00
num_weeks: 10
extra_exam_week: true

cal_dates: >                                                                    
  [                                                                            
    {"label":"W25 1st day of instruction", "date":"2025-01-06" },
    {"label":"Academic Integrity Contract Due", "date":"2025-01-14" },
    {"label":"W25 CS 9 MIDTERM (11 - 12:15pm)", "date":"2025-02-06" },
    {"label":"MLK Jr. Day", "date":"2025-01-20" },
    {"label":"Presidents' Day", "date":"2025-02-17" },
    {"label":"W25 instruction ends", "date":"2025-03-14" },
    {"label":"W25 CS 9 FINAL (12:00pm - 2:00pm)", "date":"2025-03-19" },                                                
    {"label":"W25 qtr ends", "date":"2025-03-21" }                              
  ]

kramdown:
   parse_block_html: true
   default_lang: cpp

exclude:
   - vendor
   - _hwk/keep
   - _lab/keep
   - _exam/keep
   - _lectures/keep
   - _info/keep        
include:
   - _pages
   
timezone: America/Los_Angeles

collections:
  hwk:
    output: true
    permalink: /hwk/:path/
    last_before: false
  lab:
    output: true
    permalink: /lab/:path/
    last_before: false
  labWIP:
    output: true
    permalink: /labWIP/:path/
    last_before: false
  exam:
    output: true
    permalink: /exam/:path/
  info:
    output: true
    permalink: /info/:path/
  lectures:
    output: true
    permalink: /lectures/:path/


defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: default
  - 
    scope:
      path: ""
      type: lectures
    values:
      layout: lecture
  - 
    scope:
      path: ""
      type: hwk
    values:
      layout: hwk
  - 
    scope:
      path: ""
      type: lab
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: labWIP
    values:
      layout: lab
  - 
    scope:
      path: ""
      type: exam
    values:
      layout: exam_info
  - 
    scope:
      path: ""
      type: info
    values:
      layout: default
  -
    scope:
      path: "syllabus.md"
      type: info
    values:
      layout: handout
